### ISSUE TITLE
redirect.html is missing

### ISSUE THREAD

**Issue by pratiksha2211** [omichelsen/blog-social-signin-spa-jwt-server#2]
Hello I have download the code and run index.html file then do login with facebook by adding credential..

It will show following error

The requested URL blog-social-signin-spa-jwt-server-master/redirect.html was not found on this server.

Because there is no redirect.html exists in you code

please help me how to solve this

**Comment by omichelsen** [comment]
I have added a `redirect.html` file to this repo as example.
